### ISSUE TITLE
support/fuse-support/users.properties

### ISSUE THREAD

**Issue by bkemp** [DataVirtualizationByExample/dv-fuse-integration-demo#1]
The file is an xml file, not a properties file. Can't log in. Using user.properties from a local install. I'll push it back, I you want.

--bk

**Comment by bkemp** [comment]
I see the html renders users.properties in a browser...was it copied from a browser, maybe?

**Comment by kpeeples** [comment]
yes please replace the users.properties.  looks like something happened to it.
